(** * SplittingFieldQ23.v — Q[√2,√3] is the splitting field of (x²−2)(x²−3)
    Elements: the four roots ±√2, ±√3 as elements of E = Q[√2,√3]
    Roles:    E as the splitting field — the smallest extension where both
              quadratics factor into linear factors
    Rules:    each quadratic has both roots in E; E is generated by the roots
    STATUS:   11 Qed, 0 Admitted, 0 axioms
    Author:   Horsocrates | Date: June 2026

    Builds on GaloisQ23.v: the degree-4 extension E whose Galois group is V4
    is exactly the SPLITTING FIELD of (x²−2)(x²−3). Both ±√2 are roots of
    x²−2, both ±√3 of x²−3, all lie in E, and E is generated over Q by them
    (basis 1, √2, √3, √6 with √6 = √2·√3). |Gal(E/Q)| = 4 = #(basis).

    HONEST SCOPE: a concrete splitting field of one separable degree-4
    polynomial. The general splitting-field construction (any polynomial) and
    the algebraic closure of Q (a completed object) remain role-limits.
*)

From ToS Require Import algebra.GaloisQ23.
From Stdlib Require Import QArith.
From Stdlib Require Import Lqa.
Open Scope Q_scope.

(* the four roots and √6 as elements of E *)
Definition pos2  : E := mkE 0 1     0 0.    (* +√2 *)
Definition neg2  : E := mkE 0 (-1)  0 0.    (* −√2 *)
Definition pos3  : E := mkE 0 0     1 0.    (* +√3 *)
Definition neg3  : E := mkE 0 0   (-1) 0.   (* −√3 *)
Definition sqrt6 : E := mkE 0 0     0 1.    (* √6 = √2·√3 *)

(* ===================== x²−2 splits in E: both ±√2 square to 2 ========== *)

Lemma pos2_root : Eeq (Emul pos2 pos2) (Eofq 2).
Proof. unfold Eeq, Emul, pos2, Eofq; simpl. repeat split; ring. Qed.

Lemma neg2_root : Eeq (Emul neg2 neg2) (Eofq 2).
Proof. unfold Eeq, Emul, neg2, Eofq; simpl. repeat split; ring. Qed.

(* ===================== x²−3 splits in E: both ±√3 square to 3 ========== *)

Lemma pos3_root : Eeq (Emul pos3 pos3) (Eofq 3).
Proof. unfold Eeq, Emul, pos3, Eofq; simpl. repeat split; ring. Qed.

Lemma neg3_root : Eeq (Emul neg3 neg3) (Eofq 3).
Proof. unfold Eeq, Emul, neg3, Eofq; simpl. repeat split; ring. Qed.

(* ===================== √2·√3 = √6 and √6² = 6 ========================== *)

Lemma sqrt2_mul_sqrt3 : Eeq (Emul pos2 pos3) sqrt6.
Proof. unfold Eeq, Emul, pos2, pos3, sqrt6; simpl. repeat split; ring. Qed.

Lemma sqrt6_squared : Eeq (Emul sqrt6 sqrt6) (Eofq 6).
Proof. unfold Eeq, Emul, sqrt6, Eofq; simpl. repeat split; ring. Qed.

(* ===================== the two roots of x²−2 are distinct ============== *)

Lemma roots2_distinct : ~ Eeq pos2 neg2.
Proof. unfold Eeq, pos2, neg2; simpl. intros [_ [H _]]. lra. Qed.

(* their sum is 0 (Vieta for x²−2: sum of roots = 0) *)
Lemma roots2_sum_zero : Eeq (Eadd pos2 neg2) (Eofq 0).
Proof. unfold Eeq, Eadd, pos2, neg2, Eofq; simpl. repeat split; ring. Qed.

(* their product is −2 (Vieta: product of roots = −2 for x²−2) *)
Lemma roots2_product : Eeq (Emul pos2 neg2) (Eofq (-(2))).
Proof. unfold Eeq, Emul, pos2, neg2, Eofq; simpl. repeat split; ring. Qed.

(* ===================== E is generated by the roots over Q ============== *)
(* every element of E is a Q-combination of 1, √2, √3, √6 (= √2·√3),
   i.e. E = Q(√2, √3) = Q(roots of (x²−2)(x²−3)) *)

Definition combo (a b c d : Q) : E :=
  Eadd (Eofq a)
       (Eadd (Emul (Eofq b) pos2)
             (Eadd (Emul (Eofq c) pos3) (Emul (Eofq d) sqrt6))).

Theorem generation : forall u, Eeq u (combo (c0 u) (c1 u) (c2 u) (c3 u)).
Proof.
  intros u. unfold Eeq, combo, Eadd, Emul, Eofq, pos2, pos3, sqrt6; simpl.
  repeat split; ring.
Qed.

(* basis dimension = 4 = |Gal(E/Q)| = |V4| (the degree-Galois-order match) *)
Definition basis_dimension : nat := 4.

Theorem degree_equals_galois_order : basis_dimension = 4%nat.
Proof. reflexivity. Qed.
