(** * ChomskyHierarchy.v — the Chomsky hierarchy as a LADDER of role-limits; regular ⊊ context-free
      Extends Phase 3 (regular = the Element floor) upward: the language classes form a graded
      finitization ladder — regular (finite memory, Element floor, decidable membership) ⊊
      context-free (a stack) ⊊ context-sensitive ⊊ recursively-enumerable (full computation =
      the halting role-limit, cs/HaltingRoleLimit.v).  Each rung adds memory = climbs the
      Element/role-limit gradient.

      The PROVEN rung: regular ⊊ context-free, concretely.  {a^n b^n} is context-free — generated by
      the CFG S → ε | a S b (here as the inductive predicate CFG_anbn) — but NOT regular (no finite
      DFA recognises it, cs/PumpingPigeonhole.no_dfa_for_anbn_unconditional).

    Honest gaps: the top (RE = halting) is cited (cs/HaltingRoleLimit.halts is Σ1/RE membership),
    context-sensitive (LBA) and Kleene's regex↔DFA equivalence are NOT formalised.

    Reuses cs/RegularElementFloor.v (accepts), cs/PumpingRoleLimit.v (In_L, word_a, word_b),
    cs/PumpingPigeonhole.v (no_dfa_for_anbn_unconditional).  Honest level: classical (methods +
    the ladder framing).  0 axioms.

    Elements: words; the grammar CFG_anbn (rules S→ε|aSb); DFAs
    Roles:    a language class (regular / context-free) = a rung-role of the hierarchy; "memory"
              (finite / stack / tape) = a role
    Rules:    generation by the grammar (cfg_eps/cfg_wrap); DFA recognition; the pumping wall

    ============ E/R/R разбор ============
      Rules (L5): порождение грамматикой (cfg_eps/cfg_wrap); распознавание DFA; pumping-стена.
      Roles (L4): класс языка (регулярный/контекстно-свободный) = роль-ярус иерархии; «память» = роль.
      Elements  : слова; грамматика CFG_anbn; DFA.
    ДИАГНОСТИКА (P4): иерархия Хомского = ЛЕСТНИЦА role-limit'ов: регулярные = Element-пол (конечная
      память, разрешимо, Ф3); контекстно-свободные = ярус выше (стек); …; рекурсивно-перечислимые
      (тип-0) = halting role-limit-верх (= наш halts, Ф0).  Каждый ярус добавляет память = поднимается
      по role-limit-градиенту.  ДОКАЗАННЫЙ ярус: регулярные ⊊ контекстно-свободные (a^n b^n — CFG-
      порождён, но не-DFA-распознаваем).  Честно: верх (RE=halting) — цитата; LBA и regex↔DFA — gap.

    STATUS: 8 Qed, 0 Admitted, 0 axioms
    Author: Horsocrates | Date: June 2026
*)

From Stdlib Require Import List.
Import ListNotations.
From ToS Require Import cs.RegularElementFloor.
From ToS Require Import cs.PumpingRoleLimit.
From ToS Require Import cs.PumpingPigeonhole.

(* ===================================================================== *)
(*  {a^n b^n} as a context-free grammar (the inductive predicate)          *)
(* ===================================================================== *)

(** The CFG  S → ε | a S b  (a = false, b = true), as an inductive predicate. *)
Inductive CFG_anbn : list bool -> Prop :=
  | cfg_eps  : CFG_anbn []
  | cfg_wrap : forall w, CFG_anbn w -> CFG_anbn (false :: w ++ [true]).

Lemma repeat_snoc : forall (A : Type) (a : A) (n : nat),
  repeat a n ++ [a] = repeat a (S n).
Proof.
  intros A a n. induction n as [| k IHk]; simpl; [reflexivity | rewrite IHk; reflexivity].
Qed.

Lemma anbn_succ : forall n,
  word_a (S n) ++ word_b (S n) = false :: (word_a n ++ word_b n) ++ [true].
Proof.
  intro n. unfold word_a, word_b. simpl.
  rewrite <- app_assoc, repeat_snoc. reflexivity.
Qed.

(** The grammar generates exactly {a^n b^n} (= PumpingRoleLimit.In_L). *)
Lemma CFG_anbn_to_InL : forall w, CFG_anbn w -> In_L w.
Proof.
  intros w H. induction H.
  - exists 0. reflexivity.
  - destruct IHCFG_anbn as [n Hn]. exists (S n). subst w. symmetry. apply anbn_succ.
Qed.

Lemma InL_to_CFG_anbn : forall w, In_L w -> CFG_anbn w.
Proof.
  intros w [n Hn]. subst w. induction n.
  - simpl. apply cfg_eps.
  - rewrite anbn_succ. apply cfg_wrap. exact IHn.
Qed.

Lemma CFG_anbn_iff_In_L : forall w, CFG_anbn w <-> In_L w.
Proof. intro w. split; [apply CFG_anbn_to_InL | apply InL_to_CFG_anbn]. Qed.

Example anbn_2 : CFG_anbn [false; true].
Proof. apply (cfg_wrap []). apply cfg_eps. Qed.

Example anbn_4 : CFG_anbn [false; false; true; true].
Proof. apply (cfg_wrap [false; true]). apply anbn_2. Qed.

(* ===================================================================== *)
(*  The separation: regular ⊊ context-free                                *)
(* ===================================================================== *)

(** A language is regular if some finite-state DFA recognises it. *)
Definition regular_recognized (L : list bool -> Prop) : Prop :=
  exists (Q : Type) (eqdecQ : forall x y : Q, {x = y} + {x <> y})
         (delta : Q -> bool -> Q) (acc : Q -> bool) (q0 : Q) (enum : list Q),
    (forall q, In q enum) /\ (forall w, accepts delta acc q0 w = true <-> L w).

(** ★ REGULAR ⊊ CONTEXT-FREE: {a^n b^n} is context-free (the grammar) but not regular (no DFA). *)
Theorem regular_subsetneq_context_free :
  (CFG_anbn [] /\ forall w, CFG_anbn w -> CFG_anbn (false :: w ++ [true]))
  /\ ~ regular_recognized (fun w => CFG_anbn w).
Proof.
  split.
  - split; [exact cfg_eps | exact cfg_wrap].
  - intros [Q [eqdec [delta [acc [q0 [enum [Hcomplete Hrec]]]]]]].
    apply (no_dfa_for_anbn_unconditional Q eqdec delta acc q0 enum Hcomplete).
    intro w. split.
    + intro Ha. apply (proj1 (CFG_anbn_iff_In_L w)). apply (proj1 (Hrec w)). exact Ha.
    + intro HL. apply (proj2 (Hrec w)). apply (proj2 (CFG_anbn_iff_In_L w)). exact HL.
Qed.

(** The ladder, summarised.  Bottom rung PROVEN: regular (Element floor, decidable membership —
    cs/RegularElementFloor.v) ⊊ context-free (a stack — CFG_anbn).  Climbing: context-free ⊊
    context-sensitive (LBA — not formalised) ⊊ recursively-enumerable (type-0 = Turing/λ; membership
    = cs/HaltingRoleLimit.halts, Σ1, the role-limit TOP — undecidable, grounded in real programs by
    cs/LambdaGrounding.v).  So the Chomsky hierarchy is one graded Element/role-limit gradient: each
    rung adds memory, the bottom is the decidable Element floor, the top is the halting role-limit. *)

Print Assumptions regular_subsetneq_context_free.
