(** * BackgroundIndependence.v — "gravity = Rule-object" thread 3: background independence = the metric
       (a Rule) is CONSTITUTED FROM the Roles (Sym^2(Roles), H3 ; or order+number, Sorkin), never posited
       prior to them.  Geometry = relations.  Bottoms out in L5 + P4.

    THESIS.
    A background = a fixed Rule (metric) assumed PRIOR to the systems on it (QFT-on-curved-spacetime).
    E/R/R forbids this: Rules come AFTER Roles (L5: Rules > Roles), so the metric cannot be given before
    the Roles it governs — it is CONSTITUTED from them.  Concretely the metric = Sym^2(Roles) (H3): a
    FUNCTION of the role-vectors, genuinely depending on them (not a constant fixed background); and the
    geometric interval = the NUMBER the causal ORDER puts between events (Sorkin), computed from the
    relational data, not from a background metric.

    ============ E/R/R разбор ============
      Elements : энергия-импульс/содержание, которое геометрия отслеживает (источник G=8πT).
      Roles    : направления/позиции (векторы); метрика — их симметричное спаривание.
      Rules    : метрика g = Sym^2(Роли) — ФУНКЦИЯ Ролей, не независимый вход; геометрия = порядок+число.
      ДИАГНОСТИКА (L5+P4): фон = Правило, данное ДО Ролей = инверсия конститутивного порядка (P4-семейная
      «основание-как-продукт», брат инверсии уровней нити 1). Метрика построена ИЗ Ролей (убери Роли — метрики
      нет); геометрия считывается с порядка+числа (Sorkin/Маламент). Дно: Правила из Ролей (L5) + нет
      завершённой априорной арены (P4). Уровень: `новое обрамление известного`.

    STATUS: 9 Qed, 0 Admitted, 0 axioms  (self-contained: Stdlib only)
    Author: Horsocrates (experiment) | Date: June 2026
*)

From Stdlib Require Import QArith Lqa Arith Lia.

(* ===================================================================== *)
(*  Geometry from ORDER + NUMBER (Sorkin), not from a background metric     *)
(* ===================================================================== *)

Local Open Scope nat_scope.

(** The geometric interval = the NUMBER of points the causal order puts strictly between two events
    = proper time (CausalOrderGeometry).  Computed FROM the order, not given. *)
Definition interval_card (lo hi : nat) : nat := hi - lo - 1.

(** ★ The geometric datum is COMPUTED from the order positions. *)
Lemma geometry_from_order : interval_card 0 4 = 3.
Proof. reflexivity. Qed.

(** ★ The geometry TRACKS the relational data: a different order gives a different geometry
    (no fixed stage — the geometry is generated by order+number). *)
Lemma geometry_tracks_order : interval_card 0 4 <> interval_card 0 2.
Proof. discriminate. Qed.

(* ===================================================================== *)
(*  The metric = Sym^2(Roles): a FUNCTION of the role-vectors (H3)          *)
(* ===================================================================== *)

Open Scope Q_scope.

(** The metric between two Roles (direction-vectors in Q^3) = their symmetric inner product
    = the Sym^2(Roles) pairing (H3).  It takes the Roles as INPUT — no Roles, no metric. *)
Definition metric (a b c x y z : Q) : Q := a*x + b*y + c*z.

(** ★ The metric is SYMMETRIC (Sym^2, the Rule of mutual measurement). *)
Lemma metric_symmetric : forall a b c x y z, metric a b c x y z == metric x y z a b c.
Proof. intros. unfold metric. ring. Qed.

(** ★ BACKGROUND INDEPENDENCE (i): the metric genuinely DEPENDS on the Roles —
    <e1,e1> = 1 but <e1,e2> = 0, so the metric tracks the role-data, it is not blind/constant. *)
Lemma metric_depends_on_roles :
  ~ (metric 1 0 0 1 0 0 == metric 1 0 0 0 1 0).
Proof. unfold metric. lra. Qed.

(** ★★ BACKGROUND INDEPENDENCE (ii): the relational metric is NOT any fixed background constant k —
    no constant function can equal it, because it varies with the Roles.  The metric is constituted
    from the Roles, never a pre-given stage. *)
Lemma relational_not_fixed_background : forall k : Q,
  ~ (forall a b c x y z, metric a b c x y z == k).
Proof.
  intros k H.
  pose proof (H 1 0 0 1 0 0) as H1.   (* metric e1 e1 == k  i.e. 1 == k *)
  pose proof (H 1 0 0 0 1 0) as H2.   (* metric e1 e2 == k  i.e. 0 == k *)
  unfold metric in H1, H2. lra.
Qed.

(* ===================================================================== *)
(*  CAPSTONE                                                               *)
(* ===================================================================== *)

(** Background independence: the metric (a Rule) is constituted FROM the Roles, never posited prior:
      (order+number)  the geometric interval is COMPUTED from the causal order (Sorkin), tracking it;
      (Sym^2)         the metric is the symmetric pairing of the Role-vectors (H3) — a function of them;
      (depends)       the metric genuinely varies with the Roles (not blind/constant);
      (not fixed)     NO fixed background constant equals it — it is constituted, not pre-given.
    Geometry = relations; remove the Roles and there is no metric.  Bedrock: Rules from Roles (L5) +
    no completed prior arena (P4). *)
Theorem background_independence :
  (interval_card 0 4 = 3)%nat
  /\ (interval_card 0 4 <> interval_card 0 2)%nat
  /\ (forall a b c x y z, metric a b c x y z == metric x y z a b c)
  /\ (~ (metric 1 0 0 1 0 0 == metric 1 0 0 0 1 0))
  /\ (forall k : Q, ~ (forall a b c x y z, metric a b c x y z == k)).
Proof.
  split. exact geometry_from_order.
  split. exact geometry_tracks_order.
  split. exact metric_symmetric.
  split. exact metric_depends_on_roles.
  exact relational_not_fixed_background.
Qed.
