(** * ERRLevelTower.v — the tower of level-lifts is a PROCESS with no completed colimit (P4).

    ERRLevelFunctor made the level-bump fs_lift a full faithful functor.  Iterating it gives the
    TOWER  Sys → lift Sys → lift² Sys → …  — a chain of full embeddings, all sharing ONE carrier,
    climbing the level hierarchy.  This file establishes the deep vertical fact: the tower has NO
    completed colimit — there is no "level ω" system bounding all stages — because Level is inductively
    generated (LS only, no limit level).  That is P4 (no completed infinity of levels) made precise on
    the level functor, and an instance of H1 (each finite stage is actual; the completed tower is the
    unattained role-limit).

    ============================== E/R/R разбор ==============================
    Rules (the generative rule first):
      the tower is generated by ITERATING the level-bump (lift_iter); the rule "re-situate one level
      up", applied n times.  The carrier-content is invariant; only the LEVEL climbs (by exactly one
      each step).
    Roles (L4): lift_iter (the iterated functor) over a fixed carrier; lvl_iter (the level climb);
      level_depth (the height measure).
    Elements (L1+P4): the system Sys (same carrier at every stage); the finite stages.
    P4 diagnostic (could it be otherwise?):
      the tower is a PROCESS — each finite stage lift_iter n Sys is an actual system at an actual
      finite-depth level; the COMPLETED tower (a level-ω system bounding all stages) does NOT exist,
      because Level is inductively generated (LS, no limit level).  no_completed_tower is exactly this.
    Honesty wall:
      the non-completion is P4/H1 BY DESIGN, not a limitation — there simply is no limit level.  The
      carrier is invariant (lift_iter_elements: one system climbing); what is unbounded is only the
      level-depth (the Species-II / role-limit pattern of RoleLimitSpecies, here in nat to stay self-
      contained — the ℚ-valued SingularLimit is the same shape).  get_Roles invariance is heterogeneous
      in its type (the carrier is dependent), so only the (well-typed) carrier invariance is stated.
      Reuses ERRActualization (fs_lift, lift_elements) + Core_ERR (level_depth).  0 axioms.

    STATUS: 7 Qed, 0 Admitted, 0 axioms
    Author: Horsocrates | Date: June 2026
*)

From ToS Require Import TheoryOfSystems_Core_ERR.
From ToS Require Import foundation.ERRActualization.   (* fs_lift, lift_elements *)
From Stdlib Require Import Lia.

Open Scope nat_scope.

Arguments fs_constitution {L}.
Arguments fs_domain {L}.
Arguments fs_relations {L}.
Arguments fs_functional {L}.
Arguments fs_element_level {L}.
Arguments fs_level_valid {L}.

(* ===================================================================== *)
(*  The iterated lift and the climbing level                               *)
(* ===================================================================== *)

(** The level climbed n steps up. *)
Fixpoint lvl_iter (n : nat) (L : Level) : Level :=
  match n with
  | O => L
  | Datatypes.S k => LS (lvl_iter k L)
  end.

(** The system lifted n levels up — the SAME triad, climbing the hierarchy. *)
Fixpoint lift_iter (n : nat) {L : Level} (Sys : FunctionalSystem L)
  : FunctionalSystem (lvl_iter n L) :=
  match n with
  | O => Sys
  | Datatypes.S k => fs_lift (lift_iter k Sys)
  end.

(* ===================================================================== *)
(*  The carrier is invariant; the level strictly climbs                    *)
(* ===================================================================== *)

(** ★★ The carrier is preserved through the WHOLE tower: one system, climbing levels. *)
Lemma lift_iter_elements : forall (n : nat) {L} (Sys : FunctionalSystem L),
  get_Elements (lift_iter n Sys) = get_Elements Sys.
Proof.
  intros n. induction n as [|k IH]; intros L Sys.
  - reflexivity.
  - exact (eq_trans (lift_elements (lift_iter k Sys)) (IH L Sys)).
Qed.

(** ★ Each step climbs exactly one level. *)
Lemma tower_climbs : forall (n : nat) (L : Level),
  level_depth (lvl_iter (Datatypes.S n) L) = Datatypes.S (level_depth (lvl_iter n L)).
Proof. intros n L. reflexivity. Qed.

(** The depth after n steps = n + the base depth. *)
Lemma lvl_iter_depth : forall (n : nat) (L : Level),
  level_depth (lvl_iter n L) = n + level_depth L.
Proof.
  intros n. induction n as [|k IH]; intro L.
  - reflexivity.
  - simpl. rewrite IH. reflexivity.
Qed.

(** Every level has positive (finite, ≥ 1) depth. *)
Lemma level_depth_pos : forall L, 1 <= level_depth L.
Proof. induction L; simpl; lia. Qed.

(* ===================================================================== *)
(*  No completed tower (P4)                                                *)
(* ===================================================================== *)

(** ★★ The tower is UNBOUNDED: it exceeds the depth of any given level. *)
Lemma tower_unbounded : forall {L} (m : nat),
  exists n, m < level_depth (lvl_iter n L).
Proof.
  intros L m. exists (Datatypes.S m). rewrite lvl_iter_depth.
  pose proof (level_depth_pos L). lia.
Qed.

(** ★★★ NO COMPLETED TOWER: there is no level M bounding all stages of the tower — so the tower has
    no colimit object in the hierarchy.  This is P4 (no completed infinity of levels): Level is
    inductively generated (LS, no limit level), so the ascending tower is a genuine PROCESS, never a
    finished object.  The unbounded depth is the role-limit side of H1; each finite stage (with its
    fixed carrier) is the Element side. *)
Lemma no_completed_tower : forall {L},
  ~ exists M : Level, forall n, level_depth (lvl_iter n L) <= level_depth M.
Proof.
  intros L [M HM].
  destruct (tower_unbounded (L:=L) (level_depth M)) as [n Hn].
  specialize (HM n). lia.
Qed.

(* ===================================================================== *)
(*  CAPSTONE                                                               *)
(* ===================================================================== *)

(** ★★★ THE LEVEL TOWER IS A PROCESS, NOT A COMPLETED OBJECT.
      (carrier)    the carrier is invariant through the whole tower — one system climbing;
      (climbs)     each step adds exactly one level;
      (unbounded)  the tower exceeds the depth of any given level;
      (no colimit) no level bounds all stages — the completed tower does not exist (P4).
    The full-embedding functor (ERRLevelFunctor) iterated gives an ascending ω-chain with the same
    carrier and strictly increasing level, which NEVER completes: P4 (no limit level) = H1 (the
    completed tower is the unattained role-limit; each finite stage is the actual Element side). *)
Theorem err_level_tower :
  (forall (n : nat) (L : Level) (Sys : FunctionalSystem L),
     get_Elements (lift_iter n Sys) = get_Elements Sys)
  /\ (forall (n : nat) (L : Level),
        level_depth (lvl_iter (Datatypes.S n) L) = Datatypes.S (level_depth (lvl_iter n L)))
  /\ (forall (L : Level) (m : nat), exists n, m < level_depth (lvl_iter n L))
  /\ (forall (L : Level), ~ exists M : Level, forall n, level_depth (lvl_iter n L) <= level_depth M).
Proof.
  split; [ | split; [ | split ] ].
  - intros n L Sys. exact (@lift_iter_elements n L Sys).
  - intros n L. exact (tower_climbs n L).
  - intros L m. exact (@tower_unbounded L m).
  - intros L. exact (@no_completed_tower L).
Qed.

Print Assumptions err_level_tower.

(* ========================================================================= *)
(*  SUMMARY                                                                    *)
(*  7 Qed, 0 Admitted, 0 axioms.                                             *)
(*  The tower of iterated level-lifts is a process with no completed colimit.  *)
(*  lvl_iter / lift_iter (the climbing level + the iterated full-embedding     *)
(*  functor).  lift_iter_elements (carrier invariant through the whole tower — *)
(*  one system climbing).  tower_climbs (each step +1 level) + lvl_iter_depth  *)
(*  (depth = n + base) + level_depth_pos.  tower_unbounded (exceeds any level) *)
(*  + no_completed_tower (no level bounds all stages — P4: no limit level).    *)
(*  Capstone err_level_tower.  The ascending ω-chain (same carrier, strictly   *)
(*  climbing level) never completes: P4 (Level is inductively generated, no    *)
(*  limit level) = H1 (the completed tower is the unattained role-limit; each  *)
(*  finite stage is the actual Element side).                                  *)
(* ========================================================================= *)
