(** * ReflectionRecursion.v — Reflection as Recursion of Reasoning (ToS System)

    Formalizes the adjudicated derivation of Domain 6 (working journal
    AR6-V1..V12, 2026-07-27): reflection is NOT a seventh operation beside
    the five domains — it is reasoning itself with experience as its goal,
    launched from the position of the witness's consciousness above a slice
    of the mental field.  "Domain by place in the path, recursion by
    mechanism."  Includes the Domain-5 outcome checks (abstention = two
    checks, AR5-V5) and defect inheritance up the ladder (AR5-V6).

    Elements: step-records (nat-indexed); experience = a fixed finite trace
              (list of steps; its length = the collection-time bound);
              object = an open source (query for ever more units);
              the mental field as the canonical trace of all steps so far;
              the five-stage pipeline of reasoning.
    Roles:    object-source (query open) vs experience-trace (query closed);
              witness position above the slice (the current step observes
              the field built so far and is itself not part of it);
              trigger = signal predicate of the passive mode;
              outcome = conclusion-with-mark or abstention.
    Rules:    analysis of a fixed trace cannot exceed what was recorded
              (collection-time limit); the act of reflecting over thinking
              itself appends a step — the subject is self-generated, access
              stays open; reflection = the SAME pipeline run on a trace
              (instantiation, no new constructor); the current step is never
              inside the slice it analyzes (part is less than the whole —
              no full self-view); passive mode never mutates the trace;
              conclusion requires BOTH sufficient grounds and sufficient
              strength, missing either yields abstention; a defect at any
              rung makes every ladder built on it unsound.
    Status:   all proved; self-contained (no ToS imports).
    STATUS: 23 Qed, 0 Admitted, 0 axioms
    Author: Horsocrates | Date: July 2026
*)

From Stdlib Require Import List Bool Arith Lia.
Import ListNotations.

(* ================================================================ *)
(** ** 1. Experience vs object: presence of the subject             *)
(* ================================================================ *)

(** A step-record in the mental field. *)
Definition Step : Type := nat.

(** Experience: a FIXED finite trace — what was recorded while the
    experience lasted.  Its length is the collection-time bound. *)
Definition Trace : Type := list Step.

(** An object: an OPEN source — one may always query one more unit. *)
Definition Source : Type := nat -> Step.

(** Collecting k units from an open source. *)
Definition collect (src : Source) (k : nat) : Trace :=
  map src (seq 0 k).

(** The object's query is open: the n-th unit is always obtainable. *)
Theorem source_query_open :
  forall (src : Source) (n : nat), In (src n) (collect src (S n)).
Proof.
  intros src n. unfold collect. apply in_map.
  rewrite in_seq. lia.
Qed.

(** The experience's query is closed: beyond the recorded length there
    is nothing to fetch. *)
Theorem trace_query_closed :
  forall (t : Trace) (n : nat), length t <= n -> nth_error t n = None.
Proof.
  intros t n H. rewrite nth_error_None. exact H.
Qed.

(** Analysis of a fixed trace produces no new units: any selection is
    bounded by what was collected. *)
Theorem analysis_no_new_units :
  forall (p : Step -> bool) (t : Trace),
    length (filter p t) <= length t.
Proof.
  intros p t. induction t as [| a t IH]; simpl.
  - lia.
  - destruct (p a); simpl; lia.
Qed.

(* ================================================================ *)
(** ** 2. The exception of thinking: the subject is self-generated  *)
(* ================================================================ *)

(** The act of reflection over thinking appends its own step to the
    trace: thinking about thinking produces thinking to observe. *)
Definition reflect_act (t : Trace) (s : Step) : Trace := t ++ [s].

(** The act grows the record by exactly one step. *)
Theorem reflect_act_grows :
  forall (t : Trace) (s : Step),
    length (reflect_act t s) = S (length t).
Proof.
  intros t s. unfold reflect_act.
  induction t as [| a t IH]; simpl; [reflexivity | now rewrite IH].
Qed.

(** After any act the subject is present — access is open. *)
Theorem reflect_act_nonempty :
  forall (t : Trace) (s : Step), reflect_act t s <> [].
Proof.
  intros t s. unfold reflect_act. destruct t; simpl; discriminate.
Qed.

(** The produced step itself lies in the new field: the subject of the
    next observation is generated by the observation. *)
Theorem subject_self_generated :
  forall (t : Trace) (s : Step), In s (reflect_act t s).
Proof.
  intros t s. unfold reflect_act. apply in_or_app.
  right. simpl. auto.
Qed.

(* ================================================================ *)
(** ** 3. The field and its slices                                  *)
(* ================================================================ *)

(** The canonical field after n steps: records 0 .. n-1. *)
Definition field (n : nat) : Trace := seq 0 n.

Lemma field_length : forall n : nat, length (field n) = n.
Proof.
  intro n. unfold field.
  assert (H : forall len start, length (seq start len) = len).
  { induction len; intro start; simpl; [reflexivity | now rewrite IHlen]. }
  apply H.
Qed.

(** The field grows exactly by the observing act: step n reflects over
    the slice field n and lays itself down as the next record. *)
Theorem field_growth_is_reflection :
  forall n : nat, field (S n) = reflect_act (field n) n.
Proof.
  intro n. unfold field, reflect_act. now rewrite seq_S.
Qed.

(* ================================================================ *)
(** ** 4. Limitation: no full self-view                             *)
(* ================================================================ *)

(** The current step is not inside the slice it analyzes. *)
Theorem current_not_in_slice :
  forall n : nat, ~ In n (field n).
Proof.
  intros n H. unfold field in H. rewrite in_seq in H. lia.
Qed.

(** The slice is part of the whole... *)
Theorem slice_part_of_whole :
  forall n : nat, incl (field n) (field (S n)).
Proof.
  intros n a H. unfold field in *.
  rewrite in_seq in H. rewrite in_seq. lia.
Qed.

(** ... and strictly less than it: part is less than the whole. *)
Theorem whole_strictly_more :
  forall n : nat, length (field n) < length (field (S n)).
Proof.
  intro n. rewrite !field_length. lia.
Qed.

(** No full self-view: the grown field never fits back into the slice
    the observer analyzed — one rises above a slice, not above the field. *)
Theorem no_full_self_view :
  forall n : nat, ~ incl (field (S n)) (field n).
Proof.
  intros n H. apply (current_not_in_slice n).
  apply H. unfold field. rewrite in_seq. lia.
Qed.

(* ================================================================ *)
(** ** 5. Reflection = the same pipeline (no seventh operation)     *)
(* ================================================================ *)

(** The five stages of reasoning. *)
Inductive Stage : Type := D1 | D2 | D3 | D4 | D5.

Definition reasoning_stages : list Stage := [D1; D2; D3; D4; D5].

(** Reflection's stage list IS the reasoning stage list — by definition,
    not by coincidence: instantiation, no new constructor. *)
Definition reflection_stages : list Stage := reasoning_stages.

Theorem reflection_no_seventh :
  reflection_stages = reasoning_stages.
Proof. reflexivity. Qed.

Theorem stage_count_five : length reflection_stages = 5.
Proof. reflexivity. Qed.

Section Pipeline.
  Variables A B C D E F : Type.
  Variable d1 : A -> B.  (* recognize: what is in the records      *)
  Variable d2 : B -> C.  (* clarify: constitution of the passed way *)
  Variable d3 : C -> D.  (* frame: which slice, which measure       *)
  Variable d4 : D -> E.  (* compare: way against rules, way vs ways *)
  Variable d5 : E -> F.  (* conclude: bounds, pattern, verdict      *)

  Definition run (a : A) : F := d5 (d4 (d3 (d2 (d1 a)))).
End Pipeline.

(** Reflection is the SAME run, whose input type is a trace. *)
Definition reflection_run (B C D E F : Type)
  (d1 : Trace -> B) (d2 : B -> C) (d3 : C -> D)
  (d4 : D -> E) (d5 : E -> F) : Trace -> F :=
  run Trace B C D E F d1 d2 d3 d4 d5.

Theorem reflection_is_instantiation :
  forall (B C D E F : Type)
         (d1 : Trace -> B) (d2 : B -> C) (d3 : C -> D)
         (d4 : D -> E) (d5 : E -> F) (t : Trace),
    reflection_run B C D E F d1 d2 d3 d4 d5 t
    = run Trace B C D E F d1 d2 d3 d4 d5 t.
Proof. reflexivity. Qed.

(* ================================================================ *)
(** ** 6. Two modes: passive watch and the trigger                  *)
(* ================================================================ *)

(** Passive mode: the witness watches the trace through a signal
    predicate; the trace itself is returned untouched. *)
Definition passive (p : Step -> bool) (t : Trace) : Trace * bool :=
  (t, existsb p t).

Theorem passive_no_mutation :
  forall (p : Step -> bool) (t : Trace), fst (passive p t) = t.
Proof. intros p t. reflexivity. Qed.

(** The trigger fires exactly when some recorded step carries the
    signal — the sound signal of the passive mode. *)
Theorem trigger_sound :
  forall (p : Step -> bool) (t : Trace),
    snd (passive p t) = true <-> exists s, In s t /\ p s = true.
Proof.
  intros p t. unfold passive. simpl. apply existsb_exists.
Qed.

(** The trigger opens a total choice: standard reaction or pause. *)
Inductive Reaction : Type := RStandard | RPause.

Theorem reaction_choice_total :
  forall r : Reaction, r = RStandard \/ r = RPause.
Proof. intro r. destruct r; auto. Qed.

(* ================================================================ *)
(** ** 7. Domain-5 outcome: two checks and defect inheritance       *)
(* ================================================================ *)

(** The outcome of a conclusion attempt. *)
Inductive Outcome : Type := OConclude | OAbstain.

(** Two checks hold the outcome: sufficient grounds for the conclusion
    and sufficient strength to mark it. *)
Definition verdict (grounds strength : bool) : Outcome :=
  if grounds then (if strength then OConclude else OAbstain)
  else OAbstain.

Theorem conclude_needs_both :
  forall g s : bool, verdict g s = OConclude <-> g = true /\ s = true.
Proof.
  intros g s. destruct g, s; simpl; split; intro H;
    try discriminate; intuition discriminate.
Qed.

Theorem abstain_iff_missing :
  forall g s : bool, verdict g s = OAbstain <-> g = false \/ s = false.
Proof.
  intros g s. destruct g, s; simpl; split; intro H;
    try discriminate; intuition discriminate.
Qed.

(** The ladder: rung n+1 is built on rung n; soundness of the ladder
    up to n = no defect at any rung 0..n. *)
Fixpoint ladder_sound (d : nat -> bool) (n : nat) : bool :=
  match n with
  | 0 => negb (d 0)
  | S m => andb (negb (d (S m))) (ladder_sound d m)
  end.

(** A defect at any rung is inherited by every ladder built on it. *)
Theorem defect_inherits :
  forall (d : nat -> bool) (n m : nat),
    m <= n -> d m = true -> ladder_sound d n = false.
Proof.
  intros d n. induction n as [| n IH]; intros m Hle Hd.
  - assert (m = 0) by lia; subst. simpl. now rewrite Hd.
  - simpl. inversion Hle; subst.
    + now rewrite Hd.
    + rewrite (IH m); auto. apply andb_false_r.
Qed.

(** Conversely, a sound ladder has no defect at any of its rungs. *)
Theorem sound_no_defect :
  forall (d : nat -> bool) (n : nat),
    ladder_sound d n = true ->
    forall m : nat, m <= n -> d m = false.
Proof.
  intros d n. induction n as [| n IH]; intros H m Hle.
  - assert (m = 0) by lia; subst. simpl in H.
    destruct (d 0); [discriminate | reflexivity].
  - simpl in H. apply andb_prop in H as [H1 H2].
    inversion Hle; subst.
    + destruct (d (S n)); [discriminate | reflexivity].
    + now apply IH.
Qed.

(* ================================================================ *)
(** ** 8. Capstone                                                  *)
(* ================================================================ *)

(** The canon of the derivation AR6-V11/V12:
    (i)   reflection runs the same stages — recursion by mechanism;
    (ii)  the current step never sees itself in its slice — no full
          self-view (part is less than the whole);
    (iii) the field grows exactly by the observing act — thinking
          generates its own subject;
    (iv)  the passive mode never mutates the trace. *)
Theorem reflection_canon :
  reflection_stages = reasoning_stages
  /\ (forall n : nat, ~ In n (field n))
  /\ (forall n : nat, field (S n) = reflect_act (field n) n)
  /\ (forall (p : Step -> bool) (t : Trace), fst (passive p t) = t).
Proof.
  split; [| split; [| split]].
  - reflexivity.
  - exact current_not_in_slice.
  - exact field_growth_is_reflection.
  - intros p t. reflexivity.
Qed.

Print Assumptions reflection_canon.
Print Assumptions defect_inherits.
