(** * CliffordField.v — the field of definition of the Clifford group, SPLIT by
      the finitization boundary: the two minimal quadratic extensions of ℚ that
      realise Clifford are INCOMPARABLE — ℚ[i] (Element) vs ℚ[√2] (role-limit).

    Elements: rational coordinates (a,b) of both ℚ[i] and ℚ[√2]; the named
              generators i and √2; the involution H²=I (order 2); the rational 2
              (L1 + P4)
    Roles:    ℚ[i] = the ELEMENT extension (contains i=Z₄, NOT √2) vs ℚ[√2] = the
              ROLE-LIMIT extension (contains √2 — the named-not-computed Pell
              process — NOT i); Hadamard = the gate on the role-limit (real) side;
              the phase gate = the gate on the Element side; ℚ[ζ₈] = the compositum
              where the full Clifford group lives
    Rules:    the two quadratic algebras (i²=−1 vs (√2)²=2); Hadamard
              H=(1/√2)[[1,1],[1,−1]], H²=I; and the two cross-obstructions
              √2∉ℚ[i] and i∉ℚ[√2]

    THE DEEP POINT — the finitization boundary is a statement about WHICH
    quadratic surd you adjoin.  The single-qubit Clifford group is generated by the
    phase gate S = diag(1,i) and the Hadamard H = (1/√2)[[1,1],[1,−1]].  Their
    natural fields of definition are the two quadratic extensions of ℚ — and these
    sit on OPPOSITE sides of the finitization boundary:
      · ℚ[i] is the ELEMENT extension.  It contains i, which is the order-4 Element
        of Z₄ (i⁴=1, it CLOSES — ①).  But it does NOT contain √2
        (`no_gaussian_sqrt2`): no Gaussian rational squares to 2.
      · ℚ[√2] is the ROLE-LIMIT extension.  It contains √2, the non-terminating
        Pell process — adjoined as a FORMAL Element (the coordinates stay rational),
        though its numeric value never terminates (`sqrt2_not_in_Q`): naming ≠
        computing.  But it does NOT contain i (`i_not_in_Qsqrt2`): ℚ[√2] is a REAL
        field, every square is ≥ 0, so nothing squares to −1.
    The two extensions are INCOMPARABLE — neither contains the other.  Hadamard
    lives on the role-limit side: 1/√2 = √2/2 ∈ ℚ[√2], and there H²=I (finite order
    2, `mH_invol`) — a finite-order gate whose very FIELD is a role-limit.  So the
    capstone's "ℚ-rational finite order ⟺ Z₄" (①) is a statement about the FIELD ℚ:
    admitting the √2 role-limit produces new finite-order gates (H, order 2) that
    are not in the rational Z₄ story.

    Hence the Clifford group needs the COMPOSITUM ℚ[√2,i] = ℚ[ζ₈]: one generator
    (S) Element-valued, one (H) role-limit-valued.  This is why, past the ℚ[i]
    Pauli/phase ceiling (`CliffordCeiling.v`, H7), the Clifford ladder stops being
    Element-simulable — it necessarily actualises the √2 role-limit.

    ============ E/R/R разбор ============
      Rules (L5): два квадратичных расширения ℚ[i] (i²=−1) и ℚ[√2] ((√2)²=2); H²=I;
                  обструкции √2∉ℚ[i], i∉ℚ[√2].
      Roles (L4): ℚ[i] = Element-расширение (i=Z₄, не √2); ℚ[√2] = role-limit-
                  расширение (√2 именован, не i); H = гейт role-limit-стороны;
                  ℚ[ζ₈] = компосит для всей группы Клиффорда.
      Elements  : рац. координаты (a,b); генераторы i,√2; H²=I; рациональная 2 (L1+P4).
    ДИАГНОСТИКА (P4): два минимальных расширения ℚ, реализующих Клиффорда, НЕСРАВНИМЫ и
    по разные стороны границы — ℚ[i] Element (Z₄ замыкается), ℚ[√2] role-limit (Pell не
    замыкается). Граница финитизации = какой сурд присоединён: i (Element) vs √2 (role-limit),
    не смешиваются. Клиффорду нужны ОБА ⟹ нужен role-limit. ℚ[√2] именует √2 как формальный
    Element (координаты рациональны), но значение √2 незавершаемо — именование ≠ вычисление.

    STATUS: 7 Qed, 0 Admitted, 0 axioms
    Author: Horsocrates | Date: June 2026
*)

From Stdlib Require Import QArith Qabs ZArith Lia Lqa.
From ToS Require Import analysis.Sqrt2Irrational.
Open Scope Q_scope.

(** Every rational square is non-negative (used for both cross-obstructions). *)
Lemma qsq_nonneg : forall q : Q, 0 <= q * q.
Proof.
  intro q. destruct (Qlt_le_dec q 0) as [Hlt | Hge].
  - assert (Hr : q * q == (- q) * (- q)) by ring.
    rewrite Hr. apply Qmult_le_0_compat; lra.
  - apply Qmult_le_0_compat; lra.
Qed.

(* ===================================================================== *)
(*  ℚ[√2] = (a, b) meaning a + b√2  — the ROLE-LIMIT (real) extension      *)
(*  multiplication uses (√2)² = 2                                          *)
(* ===================================================================== *)

Definition RQ : Type := (Q * Q)%type.
Definition radd (z w : RQ) : RQ := (fst z + fst w, snd z + snd w).
Definition rmul (z w : RQ) : RQ :=
  (fst z * fst w + 2 * (snd z * snd w), fst z * snd w + snd z * fst w).
Definition req (z w : RQ) : Prop := fst z == fst w /\ snd z == snd w.

Definition r0 : RQ := (0, 0).
Definition r1 : RQ := (1, 0).
Definition r2 : RQ := (0, 1).      (* the adjoined √2 *)

(** √2 is named in ℚ[√2]: the generator (0,1) squares to 2. *)
Lemma r2_is_sqrt2 : req (rmul r2 r2) (2#1, 0).
Proof. vm_compute; repeat split; reflexivity. Qed.

(** i ∉ ℚ[√2]: ℚ[√2] is a REAL field (every square ≥ 0), so nothing squares to −1.
    a + b√2 ⟹ (a+b√2)² = (a²+2b²) + 2ab√2, and a²+2b² ≥ 0 > −1. *)
Theorem i_not_in_Qsqrt2 : ~ (exists x : RQ, req (rmul x x) (-(1#1), 0)).
Proof.
  intros [[a b] H]. unfold req, rmul in H. cbn in H.
  destruct H as [H1 _].
  (* H1 : a*a + 2*(b*b) == -1 *)
  assert (Ha : 0 <= a * a) by apply qsq_nonneg.
  assert (Hb : 0 <= b * b) by apply qsq_nonneg.
  lra.
Qed.

(* ===================================================================== *)
(*  Hadamard lives on the role-limit side: H² = I over ℚ[√2]              *)
(* ===================================================================== *)

Definition RM2 : Type := (RQ * RQ * RQ * RQ)%type.   (* row-major (a b / c d) *)
Definition rm_id : RM2 := (r1, r0, r0, r1).

Definition s2  : RQ := (0, 1#2).        (* 1/√2 = √2/2 *)
Definition ns2 : RQ := (0, -(1#2)).     (* −1/√2 *)
Definition mH  : RM2 := (s2, s2, s2, ns2).   (* (1/√2)[[1,1],[1,−1]] *)

Definition rm_mul (M N : RM2) : RM2 :=
  let '(a,b,c,d) := M in
  let '(e,f,p,q) := N in
  (radd (rmul a e) (rmul b p),
   radd (rmul a f) (rmul b q),
   radd (rmul c e) (rmul d p),
   radd (rmul c f) (rmul d q)).

Definition rm_eq (M N : RM2) : Prop :=
  let '(a,b,c,d) := M in
  let '(e,f,p,q) := N in
  req a e /\ req b f /\ req c p /\ req d q.

(** H² = I: the Hadamard gate is an involution — finite order 2, but its field of
    definition ℚ[√2] is a ROLE-LIMIT extension (the 1/√2 = √2/2 entries). *)
Lemma mH_invol : rm_eq (rm_mul mH mH) rm_id.
Proof. vm_compute; repeat split; reflexivity. Qed.

(* ===================================================================== *)
(*  ℚ[i] = (a, b) meaning a + bi  — the ELEMENT extension (i²=−1)          *)
(* ===================================================================== *)

Definition GQ : Type := (Q * Q)%type.
Definition gmul (z w : GQ) : GQ :=
  (fst z * fst w - snd z * snd w, fst z * snd w + snd z * fst w).
Definition geq (z w : GQ) : Prop := fst z == fst w /\ snd z == snd w.
Definition gi  : GQ := (0, 1).        (* the imaginary unit *)
Definition gn1 : GQ := (-1, 0).       (* −1 *)

(** i² = −1: the Element extension ℚ[i] contains i (the Z₄ Element, recall ①). *)
Lemma gi_sq : geq (gmul gi gi) gn1.
Proof. vm_compute; repeat split; reflexivity. Qed.

(** √2 ∉ ℚ[i]: no Gaussian rational squares to 2.  a+bi ⟹ (a²−b²) + 2ab·i = 2 ⟹
    2ab=0 and a²−b²=2 ⟹ either a²=2 (no rational root, via √2) or b²=−2
    (impossible).  So the Element extension does NOT reach √2. *)
Theorem no_gaussian_sqrt2 : ~ (exists g : GQ, geq (gmul g g) (2#1, 0)).
Proof.
  intros [[a b] H]. unfold geq, gmul in H. cbn in H.
  destruct H as [Hre Him].
  (* Hre : a*a - b*b == 2 ;  Him : a*b + b*a == 0 *)
  assert (Hab : a * b == 0).
  { assert (Hdup : a * b + b * a == 2 * (a * b)) by ring. lra. }
  apply Qmult_integral in Hab. destruct Hab as [Ha0 | Hb0].
  - (* a = 0 ⟹ b² = −2, impossible *)
    assert (Haa : a * a == 0) by (rewrite Ha0; ring).
    assert (Hbb : b * b == -(2#1)) by lra.
    assert (Hnn : 0 <= b * b) by apply qsq_nonneg.
    lra.
  - (* b = 0 ⟹ a² = 2, no rational root *)
    apply (no_rational_sqrt2 a).
    assert (Hbb : b * b == 0) by (rewrite Hb0; ring).
    lra.
Qed.

(* ===================================================================== *)
(*  Synthesis: the Clifford field, split by the finitization boundary     *)
(* ===================================================================== *)

(** The field of definition of the Clifford group in one statement:
      (a) ℚ[√2] genuinely extends ℚ — √2 is named there (√2²=2) but irrational
          over ℚ (the role-limit, named-not-computed);
      (b) the ELEMENT extension ℚ[i] has i but NOT √2;
      (c) the ROLE-LIMIT extension ℚ[√2] has √2 but NOT i — the two are
          INCOMPARABLE, so the full Clifford group needs the compositum ℚ[ζ₈];
      (d) Hadamard lives on the role-limit (real) side: H²=I over ℚ[√2]. *)
Theorem clifford_field_synthesis :
  (req (rmul r2 r2) (2#1, 0) /\ ~ (exists q : Q, q * q == 2))
  /\ (geq (gmul gi gi) gn1 /\ ~ (exists g : GQ, geq (gmul g g) (2#1, 0)))
  /\ ~ (exists x : RQ, req (rmul x x) (-(1#1), 0))
  /\ rm_eq (rm_mul mH mH) rm_id.
Proof.
  split.
  { split; [ exact r2_is_sqrt2 | exact sqrt2_not_in_Q ]. }
  split.
  { split; [ exact gi_sq | exact no_gaussian_sqrt2 ]. }
  split; [ exact i_not_in_Qsqrt2 | exact mH_invol ].
Qed.
