(** * FinitizationBoundary.v — the demarcation theorem: QM = {ℚ-finite-actual
      core} ⊕ {provably-non-finite role-limits}.  Flagship synthesis ① of the
      ℚ-kinematics cluster.

    Elements: finite rational objects that CLOSE — Z₄ rotations, 2×2 rational
              matrices, the Pell approximants, finite commutators
    Roles:    "finitely actual" = closes in finitely many steps (Element);
              "role-limit" = provably never closes finitely (P4 process / continuum)
    Rules:    the canonical commutator [q,p]=c·I forces c=0 (trace obstruction) —
              NOT finitely realisable; a rational rotation closes IFF it is a Z₄
              exception (Niven); the continuum is the role-limit of a dense ℚ-process

    THE BOUNDARY PRINCIPLE (P4).  In ToS EVERY kinematic object is a PROCESS (a
    ℚ-sequence generated by a Rule).  The one line that divides everything is
    whether that process TERMINATES: it is **finitely actual** (an Element) exactly
    when the process CLOSES in finitely many steps, and a **role-limit** exactly
    when the process PROVABLY NEVER closes.  The "continuum" / the "infinite" /
    "irrational" are NOT completed objects here — they ARE the non-terminating
    processes; so "is it infinite / irrational" is a NON-QUESTION (P4): there are
    only processes that terminate or don't.  This file bundles the cluster's
    results as ONE demarcation, with NOTHING in between:

      OPERATOR SIDE — role-limit.  The canonical commutator [q̂,p̂] = iℏ·I cannot be
        a finite object: the two diagonal entries of any 2×2 commutator are
        negatives of each other (trace 0), so [A,B] = c·I forces c+c=0 ⟹ c=0.
        The c = iℏ ≠ 0 of quantum mechanics is therefore a role-limit — exactly
        `no_finite_ccr` (process/ProcessCanonicalCommutator.v), here in 2×2 form.

      KINEMATIC CORE — Element.  Finite-order rational rotations exist and close:
        the quarter-turn i=(0,1) has order 4 (i⁴ = identity), the Z₄ of
        ConnectionCircle.v.  These ARE finitely actual.

      KINEMATIC ROLE-LIMIT.  Every OTHER rational rotation never closes: the
        3-4-5 rotation is aperiodic (`rotation_345_aperiodic`, NivenGeneral.v).
        By the full Niven theorem a rational rotation closes IFF it is a Z₄
        exception — so the boundary between "closes" and "never closes" is sharp.

      CONTINUUM ROLE-LIMIT.  The continuum point (the 45° diagonal) is the
        role-limit of a dense ℚ-process: the Pell triangles' deviation contracts
        geometrically to 0 (`pell_e_sq_step`, PythagoreanDensity.v) yet the exact
        point is never an Element.

    No intermediate: every object is a process that either TERMINATES (closes → an
    Element) or is NON-TERMINATING (→ a role-limit).  This is the P4 ontology —
    "actual = terminating process, infinite = non-terminating process" — made into
    a theorem.

    ============ E/R/R разбор ============
      ВСЁ — ПРОЦЕСС (примитив); Element — это ТЕРМИНУС завершающегося процесса, НЕ
                  отдельная категория. Rules (L5): процесс замыкается = ЗАВЕРШАЮЩИЙСЯ
                  (терминус = Element); не замыкается = НЕЗАВЕРШАЮЩИЙСЯ = role-limit;
                  между ними — пусто.
      Roles (L4): канонический коммутатор, континуум, иррациональное, π-несоизмеримый
                  поворот = НЕЗАВЕРШАЮЩИЕСЯ процессы (role-limits); Z₄ и конечные
                  матрицы = ЗАВЕРШАЮЩИЕСЯ процессы (Элементы).
      Elements  : рациональные приближения, которые генерирует процесс (L1+P4).
    ДИАГНОСТИКА (P4): граница финитизации = ЗАВЕРШАЕТСЯ ли процесс. «Бесконечно/
    иррационально ли X» — не-вопрос: X ЕСТЬ процесс. QM = завершающееся ℚ-ядро ⊕
    охарактеризованный незавершающийся остаток.

    STATUS: 3 Qed, 0 Admitted, 0 axioms
    Author: Horsocrates | Date: June 2026
*)

From Stdlib Require Import QArith Qabs ZArith Lia Lqa.
From ToS Require Import stdlib.PythagoreanTriples.
From ToS Require Import stdlib.PythagoreanDensity.
From ToS Require Import stdlib.NivenGeneral.
Open Scope Q_scope.

(* ===== Operator side: the canonical commutator is a role-limit (2×2) ===== *)

(** The two diagonal entries of a 2×2 commutator are negatives of each other,
    so [A,B] = c·I (both diagonals = c) forces c = 0.  The canonical commutator
    [q̂,p̂] = iℏ·I (c = iℏ ≠ 0) has NO finite realisation — it is a role-limit. *)
Lemma canonical_commutator_2x2 :
  forall a12 a21 b12 b21 c : Q,
    a12*b21 - a21*b12 == c -> a21*b12 - a12*b21 == c -> c == 0.
Proof. intros a12 a21 b12 b21 c H1 H2. lra. Qed.

(* ===== Kinematic core: the quarter-turn closes (Z₄, finite order) ======== *)

Definition i_pt : Q * Q := (0, 1).

(** i⁴ = identity: the quarter-turn is finitely actual (order 4). *)
Lemma quarter_turn_closes :
  fst (cmul (cmul (cmul i_pt i_pt) i_pt) i_pt) == 1 /\
  snd (cmul (cmul (cmul i_pt i_pt) i_pt) i_pt) == 0.
Proof. unfold i_pt. split; vm_compute; reflexivity. Qed.

(* ===== The demarcation theorem ========================================== *)

(** Every object is an Element (closes finitely) or a role-limit (provably
    never closes) — nothing between.  Operator role-limit ∧ Element ∧ kinematic
    role-limit ∧ continuum role-limit, all machine-checked. *)
Theorem finitization_boundary :
  (* role-limit: canonical commutator forces c = 0 (no finite realisation) *)
  (forall a12 a21 b12 b21 c : Q,
     a12*b21 - a21*b12 == c -> a21*b12 - a12*b21 == c -> c == 0)
  /\
  (* Element: the quarter-turn closes (Z₄, order 4) *)
  (fst (cmul (cmul (cmul i_pt i_pt) i_pt) i_pt) == 1 /\
   snd (cmul (cmul (cmul i_pt i_pt) i_pt) i_pt) == 0)
  /\
  (* role-limit: the 3-4-5 rotation never closes (Niven aperiodicity) *)
  (forall k, ~ Z.divide 5 (c 6 5 (S k)))
  /\
  (* continuum role-limit: the dense Pell process's deviation contracts → 0 *)
  (forall n, 16 * (pell_e (S n) * pell_e (S n)) <= pell_e n * pell_e n).
Proof.
  split; [ exact canonical_commutator_2x2 |].
  split; [ exact quarter_turn_closes |].
  split; [ exact rotation_345_aperiodic | exact pell_e_sq_step ].
Qed.
