(** * GeneralRoot.v — the general k-th-root theorem (degree-uniform engine as a THEOREM):
      for every k ≥ 1, the k-th root of n is rational ⟺ n is a perfect k-th power.  This is the
      capstone of GeneralSqrt.v (k=2) and GeneralCbrt.v (k=3): the observation "the coprimality
      engine is degree-uniform" becomes a theorem, with degree-uniformity realized by INDUCTION
      on k (coprimality propagated under an arbitrary power).  The square and cube engines are
      derived here as the k=2,3 instances.

    Elements: a reduced fraction (a,b) with gcd a b = 1; the k-th powers zpow m k; the engine
              instances at k=2 (GeneralSqrt / √2) and k=3 (GeneralCbrt / ∛2) (L1 + P4)
    Roles:    Element side = n a perfect k-th power ⟹ ᵏ√n ∈ ℚ (terminates); role-limit = n not a
              perfect k-th power ⟹ ᵏ√n ∉ ℚ (non-terminating) — ONE boundary shape at every degree
    Rules:    b | a^k (since b | b^k for k ≥ 1); coprimality under the k-th power
              (rel_prime b (a^k), by INDUCTION on k) ⟹ b | 1 ⟹ b = 1 ⟹ n = a^k

    THE DEEP POINT — degree-uniformity is a theorem, via induction on k.  The engine
    `reduced_kth_power_integer`: a reduced fraction a/b whose k-th power is an integer n
    (a^k = n·b^k, k ≥ 1) has b = 1.  The mechanism is the SAME at every degree: b | a^k, and
    coprimality lifts to the k-th power by `rel_prime_zpow` — one inductive step (a^{S k}=a·a^k,
    rel_prime_mult) carries gcd(a,b)=1 to gcd(b,a^k)=1 for ALL k.  So "is the k-th root of n
    rational?" is the DECIDABLE Element-question "is n a perfect k-th power?" at every degree,
    by one engine (`perfect_kth_power_criterion`).  GeneralSqrt's `reduced_square_integer` and
    GeneralCbrt's `reduced_cube_integer` are the k=2,3 instances (`square_engine_instance`
    derives the square case from the general one).  The finitization boundary is stratified by
    degree (H8) yet generated by a single inductive coprimality principle.  Element = n a perfect
    k-th power; role-limit = n a non-k-th-power (ᵏ√n a non-terminating process).

    ============ E/R/R разбор ============
      Rules (L5): b∣a^k (ибо b∣b^k при k≥1); взаимная простота под k-й степенью (rel_prime b (a^k),
                  ПО ИНДУКЦИИ на k) ⟹ b∣1 ⟹ b=1 ⟹ n=a^k.
      Roles (L4): Element = n полная k-я степень ⟹ ᵏ√n∈ℚ; role-limit = n не k-я степень ⟹ ᵏ√n∉ℚ;
                  одна форма границы на КАЖДОЙ степени; reduced_square/cube_integer = инстансы k=2,3.
      Elements  : приведённая (a,b) gcd=1; k-е степени zpow m k; инстансы k=2 (√2), k=3 (∛2).
    ДИАГНОСТИКА (P4): «рационален ли k-й корень из n?» = «n полная k-я степень?» — РАЗРЕШИМЫЙ Element-вопрос
    на КАЖДОЙ степени, ОДНИМ движком. Однородность по степени (наблюдалась в CubicRoleLimit/GeneralCbrt) здесь
    ДОКАЗАНА индукцией rel_prime_zpow. √2/∛2 = role-limit-инстансы k=2,3; граница стратифицирована по степени (H8),
    но порождена единым индуктивным принципом взаимной простоты. (ℤ-капстоун; ℚ-мосты k=2,3 — в GeneralSqrt/GeneralCbrt.)

    STATUS: 9 Qed, 0 Admitted, 0 axioms
    Author: Horsocrates | Date: June 2026
*)

From Stdlib Require Import ZArith Znumtheory Lia.

Open Scope Z_scope.

(* ===================================================================== *)
(*  Integer k-th power (own Fixpoint, to keep proofs definitional)         *)
(* ===================================================================== *)

Fixpoint zpow (a : Z) (k : nat) : Z :=
  match k with
  | O => 1
  | S k' => a * zpow a k'
  end.

(** 1 to any power is 1. *)
Lemma zpow_one : forall k : nat, zpow 1 k = 1.
Proof. induction k as [| k IH]; [ reflexivity | simpl; rewrite IH; reflexivity ]. Qed.

(* ===================================================================== *)
(*  Coprimality is preserved under the k-th power (induction on k)         *)
(* ===================================================================== *)

(** Anything is coprime to 1. *)
Lemma rel_prime_b_1 : forall b : Z, rel_prime b 1.
Proof.
  intros b. apply Zis_gcd_intro.
  - apply Z.divide_1_l.
  - apply Z.divide_1_l.
  - intros x _ Hx1. exact Hx1.
Qed.

(** ★ The degree-uniformity engine: if b is coprime to a, it is coprime to a^k for EVERY k.
    One induction step (a^{S k} = a·a^k, rel_prime_mult) lifts coprimality to all degrees. *)
Lemma rel_prime_zpow : forall (a b : Z) (k : nat),
  rel_prime b a -> rel_prime b (zpow a k).
Proof.
  intros a b k H. induction k as [| k IH].
  - simpl. apply rel_prime_b_1.
  - simpl. apply rel_prime_mult; [ exact H | exact IH ].
Qed.

(** b divides b^{k+1}. *)
Lemma b_div_zpow_succ : forall (b : Z) (k : nat), (b | zpow b (S k)).
Proof. intros b k. simpl. exists (zpow b k). ring. Qed.

(* ===================================================================== *)
(*  THE CAPSTONE: a reduced fraction with integer k-th power is integer    *)
(* ===================================================================== *)

(** ★ For every k, a reduced fraction a/b (gcd a b = 1, b > 0) whose (k+1)-th power is an
    integer n (a^{k+1} = n·b^{k+1}) has denominator b = 1.  ONE engine for all degrees. *)
Lemma reduced_kth_power_integer : forall (a b n : Z) (k : nat),
  0 < b -> Z.gcd a b = 1 -> zpow a (S k) = n * zpow b (S k) -> b = 1.
Proof.
  intros a b n k Hpos Hcop Heq.
  assert (Hdivb : (b | zpow b (S k))) by apply b_div_zpow_succ.
  assert (Hdiv : (b | zpow a (S k))).
  { rewrite Heq. apply Z.divide_mul_r. exact Hdivb. }
  assert (Hrp_ba : rel_prime b a).
  { apply rel_prime_sym. red. rewrite <- Hcop. apply Zgcd_is_gcd. }
  assert (Hrp : rel_prime b (zpow a (S k))) by (apply rel_prime_zpow; exact Hrp_ba).
  assert (Hb1 : (b | 1)).
  { destruct Hrp as [_ _ Hg]. apply Hg; [ apply Z.divide_refl | exact Hdiv ]. }
  pose proof (Z.divide_pos_le b 1 ltac:(lia) Hb1) as Hle.
  lia.
Qed.

(** ★ Hence the perfect-k-th-power criterion: a reduced fraction whose (k+1)-th power is the
    integer n witnesses that n IS a perfect (k+1)-th power (n = a^{k+1}). *)
Lemma perfect_kth_power_criterion : forall (a b n : Z) (k : nat),
  0 < b -> Z.gcd a b = 1 -> zpow a (S k) = n * zpow b (S k) ->
  exists m : Z, n = zpow m (S k).
Proof.
  intros a b n k Hpos Hcop Heq.
  assert (Hb : b = 1) by (apply (reduced_kth_power_integer a b n k); assumption).
  exists a. rewrite Hb in Heq. rewrite zpow_one in Heq. lia.
Qed.

(* ===================================================================== *)
(*  The square / cube engines are the k = 2, 3 instances                   *)
(* ===================================================================== *)

(** ★ GeneralSqrt's engine recovered as the k=2 instance: the general theorem subsumes it. *)
Corollary square_engine_instance : forall a b n : Z,
  0 < b -> Z.gcd a b = 1 -> a * a = n * (b * b) -> b = 1.
Proof.
  intros a b n Hpos Hcop Heq.
  apply (reduced_kth_power_integer a b n 1%nat); try assumption.
  cbn [zpow].
  replace (a * (a * 1)) with (a * a) by ring.
  replace (n * (b * (b * 1))) with (n * (b * b)) by ring.
  exact Heq.
Qed.

(** GeneralCbrt's engine recovered as the k=3 instance. *)
Corollary cube_engine_instance : forall a b n : Z,
  0 < b -> Z.gcd a b = 1 -> a * a * a = n * (b * b * b) -> b = 1.
Proof.
  intros a b n Hpos Hcop Heq.
  apply (reduced_kth_power_integer a b n 2%nat); try assumption.
  cbn [zpow].
  replace (a * (a * (a * 1))) with (a * a * a) by ring.
  replace (n * (b * (b * (b * 1)))) with (n * (b * b * b)) by ring.
  exact Heq.
Qed.

(* ===================================================================== *)
(*  Synthesis                                                            *)
(* ===================================================================== *)

(** The degree-uniform finitization engine:
      (a) CAPSTONE — for EVERY k, a reduced fraction with integer (k+1)-th power is an integer
          (`reduced_kth_power_integer`), so such an n is a perfect (k+1)-th power
          (`perfect_kth_power_criterion`); degree-uniformity is a theorem via the induction
          `rel_prime_zpow`;
      (b) INSTANCES — the square (k=2) and cube (k=3) engines of GeneralSqrt/GeneralCbrt are
          recovered (`square_engine_instance`, `cube_engine_instance`). *)
Theorem general_root_synthesis :
  (forall (a b n : Z) (k : nat),
     0 < b -> Z.gcd a b = 1 -> zpow a (S k) = n * zpow b (S k) -> b = 1)
  /\ (forall (a b n : Z) (k : nat),
        0 < b -> Z.gcd a b = 1 -> zpow a (S k) = n * zpow b (S k) ->
        exists m : Z, n = zpow m (S k))
  /\ (forall a b n : Z, 0 < b -> Z.gcd a b = 1 -> a * a = n * (b * b) -> b = 1)
  /\ (forall a b n : Z, 0 < b -> Z.gcd a b = 1 -> a * a * a = n * (b * b * b) -> b = 1).
Proof.
  split; [ exact reduced_kth_power_integer | ].
  split; [ exact perfect_kth_power_criterion | ].
  split; [ exact square_engine_instance | exact cube_engine_instance ].
Qed.
