(** * PellDichotomy.v — why √2, √3, √5 have Pell processes but √4, √9 do not: the
      square/non-square dichotomy = rational/irrational = Element/role-limit.  The general
      principle behind the surd–Pell triad (Sqrt2/3Pell, LucasFibonacci).

      For a PERFECT SQUARE D = k², the Pell equation x²−Dy²=1 has ONLY the trivial solution
      (±1,0) — √D = k is rational, the process terminates (Element side).  For a NON-SQUARE
      D, √D is irrational and the fundamental solution generates INFINITELY many solutions
      via Brahmagupta's identity — the convergents x/y → √D, a non-terminating process
      (role-limit side).

    Elements: the integer solutions (3,2),(2,1),(9,4); the trivial (±1,0) (L1 + P4)
    Roles:    Element side (D=k² square) = √D rational, only the trivial Pell solution;
              role-limit side (D non-square) = √D irrational, infinitely many solutions =
              the role-limit process approximating √D (generated by Brahmagupta composition)
    Rules:    the Pell equation x²−Dy²=1; Brahmagupta (x²−Dy²)(u²−Dv²)=(xu+Dyv)²−D(xv+yu)²;
              the square/non-square split

    THE DEEP POINT — Pell solvability ⟺ √D irrational ⟺ D non-square ⟺ role-limit.  When
    D=k² is a square, x²−Dy²=1 factors as (x−ky)(x+ky)=1, forcing the trivial solution
    (`pell_square_trivial`) — √D=k is rational, Element side, no approximation to make.  When
    D is non-square, √D is a role-limit, and the Pell solutions form a group under
    Brahmagupta composition (`pell_brahmagupta`): from the fundamental solution, doubling
    (`pell_double`) generates an infinite tower (3,2)→(17,12)→… whose ratios x/y converge
    to √D.  Concretely (3,2) for D=2, (2,1) for D=3, (9,4) for D=5 (`pell_nonsquare_examples`)
    — and √2 is irrational (`sqrt2_role_limit`).  So the Pell solutions are the Element-side
    integer structure that GENERATES the role-limit approximation of √D.  This is the general
    principle behind the surd–Pell triad: √2,√3,√5 have Pell processes (non-square =
    irrational = role-limit); √4=2 does not (square = rational = Element).

    ============ E/R/R разбор ============
      Rules (L5): уравнение Пелля x²−Dy²=1; Брахмагупта (x²−Dy²)(u²−Dv²)=(xu+Dyv)²−D(xv+yu)²;
                  расщепление квадрат/не-квадрат.
      Roles (L4): Element (D=k² квадрат) = √D рационально, только тривиальное решение; role-limit
                  (D не квадрат) = √D иррационально, бесконечно решений = процесс приближения √D.
      Elements  : целые решения (3,2),(2,1),(9,4); тривиальное (±1,0) (L1+P4).
    ДИАГНОСТИКА (P4): разрешимость Пелля ⟺ √D иррационально ⟺ D не квадрат ⟺ role-limit; решения Пелля =
    Element-группа (Брахмагупта), порождающая role-limit-приближение x/y→√D. Общий принцип за surd-Pell-триадой.

    STATUS: 7 Qed, 0 Admitted, 0 axioms
    Author: Horsocrates | Date: June 2026
*)

From Stdlib Require Import ZArith Lia QArith.
From ToS Require Import analysis.Sqrt2Irrational.

Open Scope Z_scope.

(* ===================================================================== *)
(*  Element side: a square D gives only the trivial Pell solution         *)
(* ===================================================================== *)

(** Two integer squares differ by 1 only at 0: x²−w²=1 ⟹ w=0 (via (x−w)(x+w)=1). *)
Lemma consecutive_squares : forall x w : Z, x*x - w*w = 1 -> w = 0.
Proof.
  intros x w H.
  assert (Hfac : (x - w) * (x + w) = 1) by (rewrite <- H; ring).
  pose proof Hfac as Hfac2.
  apply Z.mul_eq_1 in Hfac.
  destruct Hfac as [Ha | Ha]; nia.
Qed.

(** ★ For a perfect square D = k², the Pell equation x²−k²y²=1 forces k·y=0 — only the
    trivial solution (√D = k is rational, Element side). *)
Theorem pell_square_trivial : forall x y k : Z,
  x*x - (k*k)*(y*y) = 1 -> k*y = 0.
Proof.
  intros x y k H. apply (consecutive_squares x (k*y)). nia.
Qed.

(* ===================================================================== *)
(*  Role-limit side: non-square D — the Brahmagupta group of solutions    *)
(* ===================================================================== *)

(** ★ Brahmagupta's identity (the ℤ[√D] norm form): Pell solutions compose, so they form a
    group — the Element-side structure that generates the role-limit approximation of √D. *)
Lemma pell_brahmagupta : forall D x y u v : Z,
  (x*x - D*(y*y)) * (u*u - D*(v*v))
  = (x*u + D*(y*v)) * (x*u + D*(y*v)) - D * ((x*v + y*u) * (x*v + y*u)).
Proof. intros. ring. Qed.

(** ★ Doubling a Pell solution gives another (the special case u,v = x,y): from x²−Dy²=1,
    (x²+Dy², 2xy) is again a solution — generating the infinite tower x/y → √D. *)
Theorem pell_double : forall D x y : Z, x*x - D*(y*y) = 1 ->
  (x*x + D*(y*y)) * (x*x + D*(y*y)) - D * ((2*x*y) * (2*x*y)) = 1.
Proof.
  intros D x y H.
  assert (Hid : (x*x + D*(y*y)) * (x*x + D*(y*y)) - D * ((2*x*y) * (2*x*y))
                = (x*x - D*(y*y)) * (x*x - D*(y*y))) by ring.
  rewrite Hid, H. ring.
Qed.

(** Concrete non-square Pell solutions: (3,2) for D=2, (2,1) for D=3, (9,4) for D=5. *)
Lemma pell_nonsquare_examples :
  3*3 - 2*(2*2) = 1 /\ 2*2 - 3*(1*1) = 1 /\ 9*9 - 5*(4*4) = 1.
Proof. repeat split; reflexivity. Qed.

(* ===================================================================== *)
(*  Role-limit: √2 (the D=2 limit) is irrational                          *)
(* ===================================================================== *)

(** √2 — the limit of the D=2 Pell convergents x/y — is irrational (the role-limit driving
    the infinite Pell process; the same √2 as the T-gate / 45°). *)
Theorem sqrt2_role_limit : ~ (exists r : Q, (r * r == 2)%Q).
Proof. exact sqrt2_not_in_Q. Qed.

(* ===================================================================== *)
(*  Synthesis                                                            *)
(* ===================================================================== *)

(** The Pell dichotomy, split by the finitization boundary:
      (a) ELEMENT — a square D=k² forces the trivial solution (k·y=0; √D rational);
      (b) Brahmagupta: Pell solutions compose (the group structure);
      (c) doubling generates the infinite tower (the role-limit process);
      (d) concrete non-square solutions (3,2),(2,1),(9,4);
      (e) ROLE-LIMIT — √2 (the D=2 limit) is irrational. *)
Theorem pell_dichotomy_synthesis :
  (forall x y k : Z, (x*x - (k*k)*(y*y) = 1 -> k*y = 0)%Z)
  /\ (forall D x y u v : Z, ((x*x - D*(y*y)) * (u*u - D*(v*v))
        = (x*u + D*(y*v)) * (x*u + D*(y*v)) - D * ((x*v + y*u) * (x*v + y*u)))%Z)
  /\ (forall D x y : Z, (x*x - D*(y*y) = 1)%Z ->
        ((x*x + D*(y*y)) * (x*x + D*(y*y)) - D * ((2*x*y) * (2*x*y)) = 1)%Z)
  /\ ((3*3 - 2*(2*2) = 1)%Z /\ (9*9 - 5*(4*4) = 1)%Z)
  /\ ~ (exists r : Q, (r * r == 2)%Q).
Proof.
  split; [ exact pell_square_trivial | ].
  split; [ exact pell_brahmagupta | ].
  split; [ exact pell_double | ].
  split; [ split; reflexivity | exact sqrt2_role_limit ].
Qed.
