# generate.ps1 - build Markdown views from the JSON shards (source of truth).
# Usage:  powershell -ExecutionPolicy Bypass -File docs\database\generate.ps1
# Reads every <cluster>.json in this folder, emits <cluster>.md + INDEX.md + _uniqueness_ranked.md.
# NOTE: this script is ASCII-only on purpose (PS 5.1 parses .ps1 as ANSI without a BOM).
#       Data (JSON, incl. Cyrillic) is read as UTF-8 and written back as UTF-8 (no BOM).

$ErrorActionPreference = 'Stop'
$dir = Split-Path -Parent $MyInvocation.MyCommand.Path
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Cell([string]$s) {
  if ($null -eq $s) { return '' }
  return ($s -replace '\|', '\|') -replace '[\r\n]+', ' '
}
function W($list, $s) { $list.Add($s) | Out-Null }

# ---- collect shards -----------------------------------------------------
$shards = Get-ChildItem -Path $dir -Filter *.json | Where-Object { $_.Name -notlike '_*' } | Sort-Object Name
$all = New-Object System.Collections.Generic.List[object]

foreach ($shard in $shards) {
  $cluster = [System.IO.Path]::GetFileNameWithoutExtension($shard.Name)
  $parsed = Get-Content $shard.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
  $records = @($parsed)
  foreach ($r in $records) { $all.Add($r) | Out-Null }

  $md = New-Object System.Collections.Generic.List[string]
  $totQ = ($records | Measure-Object -Property qed -Sum).Sum
  W $md ('# Database - cluster `{0}`' -f $cluster)
  W $md ''
  W $md ('_Generated from `{0}` by `generate.ps1` - do not edit by hand; edit the JSON._' -f $shard.Name)
  W $md ''
  $dist = (5..0 | ForEach-Object { $s = $_; $c = @($records | Where-Object { $_.uniqueness.score -eq $s }).Count; "s$s=$c" }) -join ' / '
  W $md "**$($records.Count) files / $totQ Qed.** Score distribution: $dist"
  W $md ''

  foreach ($r in ($records | Sort-Object num)) {
    W $md '---'
    W $md ''
    W $md ('## #{0} - `{1}` - score {2} ({3})' -f $r.num, $r.path, $r.uniqueness.score, $r.uniqueness.level)
    W $md ''
    W $md ('**{0}**' -f $r.title)
    W $md ''
    W $md ('- **Topic.** {0}' -f $r.topic)
    W $md ('- **Role.** {0}' -f $r.role)
    W $md ('- **Counts.** Qed {0} / Admitted {1} / axioms {2}' -f $r.qed, $r.admitted, $r.axioms)
    W $md ('- **Imports.** {0}' -f ($r.imports -join '; '))
    W $md ('- **E/R/R.** _Elements:_ {0} _Roles:_ {1} _Rules:_ {2} _P4:_ {3}' -f (Cell $r.err.elements), (Cell $r.err.roles), (Cell $r.err.rules), (Cell $r.err.p4))
    if ($r.PSObject.Properties.Name -contains 'classical_counterpart' -and $r.classical_counterpart) { W $md ('- **Classical counterpart.** {0}' -f (Cell $r.classical_counterpart)) }
    W $md ('- **Tags.** {0}' -f ($r.tags -join ', '))
    if ($r.PSObject.Properties.Name -contains 'notes' -and $r.notes) { W $md ('- **Notes.** {0}' -f $r.notes) }
    W $md ''
    W $md ('**Lemmas ({0}):**' -f $r.lemmas.Count)
    W $md ''
    W $md '| name | kind | role |'
    W $md '|---|---|---|'
    foreach ($l in $r.lemmas) { W $md ('| `{0}` | {1} | {2} |' -f (Cell $l.name), (Cell $l.kind), (Cell $l.role)) }
    W $md ''
    W $md '**Key lemmas (deep):**'
    W $md ''
    foreach ($k in $r.key_lemmas) { W $md ('- **`{0}`** - {1} _({2})_' -f $k.name, (Cell $k.analysis), ($k.tags -join ', ')) }
    W $md ''
    W $md ('**Uniqueness - score {0} ({1}).** {2}' -f $r.uniqueness.score, $r.uniqueness.level, $r.uniqueness.claim)
    W $md ('> _Caveat:_ {0}' -f $r.uniqueness.caveat)
    W $md ''
  }
  [System.IO.File]::WriteAllLines((Join-Path $dir "$cluster.md"), $md, $utf8)
  Write-Output "wrote $cluster.md ($($records.Count) files, $totQ Qed)"
}

# ---- INDEX.md (master table) -------------------------------------------
$idx = New-Object System.Collections.Generic.List[string]
$grandQ = ($all | Measure-Object -Property qed -Sum).Sum
W $idx '# Database INDEX'
W $idx ''
W $idx '_Generated by `generate.ps1`. Source of truth = the `<cluster>.json` shards._'
W $idx ''
$clusterSummary = (($all | Group-Object cluster | Sort-Object Name | ForEach-Object { "$($_.Name) ($($_.Count))" }) -join ', ')
W $idx "**$($all.Count) files catalogued / $grandQ Qed.** Clusters: $clusterSummary"
W $idx ''
W $idx '| # | file | Qed | score | level | title |'
W $idx '|---|---|---|---|---|---|'
foreach ($r in ($all | Sort-Object num)) {
  W $idx ('| {0} | `{1}` | {2} | {3} | {4} | {5} |' -f $r.num, $r.path, $r.qed, $r.uniqueness.score, $r.uniqueness.level, (Cell $r.title))
}
[System.IO.File]::WriteAllLines((Join-Path $dir 'INDEX.md'), $idx, $utf8)
Write-Output "wrote INDEX.md ($($all.Count) files, $grandQ Qed)"

# ---- _uniqueness_ranked.md (raw material for UNIQUENESS.md) -------------
$rank = New-Object System.Collections.Generic.List[string]
W $rank '# Uniqueness - ranked (raw material for UNIQUENESS.md)'
W $rank ''
W $rank '_Generated. Sorted by score desc, then file number. Use to assemble the curated UNIQUENESS.md._'
W $rank ''
W $rank '| score | level | # | file | claim | caveat |'
W $rank '|---|---|---|---|---|---|'
foreach ($r in ($all | Sort-Object @{Expression={$_.uniqueness.score}; Descending=$true}, @{Expression={$_.num}; Descending=$false})) {
  W $rank ('| {0} | {1} | {2} | `{3}` | {4} | {5} |' -f $r.uniqueness.score, $r.uniqueness.level, $r.num, $r.path, (Cell $r.uniqueness.claim), (Cell $r.uniqueness.caveat))
}
[System.IO.File]::WriteAllLines((Join-Path $dir '_uniqueness_ranked.md'), $rank, $utf8)
Write-Output 'wrote _uniqueness_ranked.md'
