# highlights2md.ps1 - generate the "Избранные результаты" block from HIGHLIGHTS vitrina lines.
# Reads a source .md whose entries carry a  <!-- ... theme="..." level="..." part="..." cost="..." show="..." -->
# line plus one vitrina sentence, emits a theme-grouped block, and (optionally) injects it between
# <!-- HL:BEGIN --> / <!-- HL:END --> markers in a target page (like catalog2md.ps1).
# Pure ASCII on purpose: Cyrillic lives only in the DATA it reads/writes, so this .ps1 needs no BOM.
param(
  [string]$Source,
  [string]$IndexOut = '',
  [string]$Inject = ''
)

$D  = [string][char]0x00B7          # middle-dot separator
$B0 = '<!-- HL:BEGIN (generated by tools/highlights2md.ps1 - do not edit by hand) -->'
$E0 = '<!-- HL:END -->'
$noBom = New-Object System.Text.UTF8Encoding($false)

$raw = [System.IO.File]::ReadAllText($Source, [System.Text.Encoding]::UTF8) -replace "`r`n","`n"
$blocks = [regex]::Split($raw, '(?m)^(?=## H\d)')

$entries = New-Object System.Collections.Generic.List[object]
foreach ($b in $blocks) {
  if ($b -notmatch '(?m)^## H\d') { continue }
  if ($b -notmatch 'theme="')     { continue }
  $theme = ([regex]::Match($b,'theme="([^"]*)"')).Groups[1].Value
  $level = ([regex]::Match($b,'level="([^"]*)"')).Groups[1].Value
  $part  = ([regex]::Match($b,'part="([^"]*)"')).Groups[1].Value
  $cost  = ([regex]::Match($b,'cost="([^"]*)"')).Groups[1].Value
  $show  = ([regex]::Match($b,'show="([^"]*)"')).Groups[1].Value
  $vit = ''
  $after = $false
  foreach ($ln in ($b -split "`n")) {
    if (-not $after) { if ($ln -match 'theme="') { $after = $true }; continue }
    if ($ln.Trim() -ne '') { $vit = $ln.Trim(); break }
  }
  $entries.Add([pscustomobject]@{ theme=$theme; level=$level; part=$part; cost=$cost; show=$show; vit=$vit })
}

# theme-grouped index block (entries whose show contains 'index'), first-seen theme order
$idx = @($entries | Where-Object { $_.show -match 'index' })
$order = @(); foreach ($e in $idx) { if ($order -notcontains $e.theme) { $order += $e.theme } }

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add($B0); $lines.Add('')
foreach ($t in $order) {
  $lines.Add('**' + $t + '.**'); $lines.Add('')
  foreach ($e in ($idx | Where-Object { $_.theme -eq $t })) {
    $meta = $e.level + ' ' + $D + ' ' + $e.part + ' ' + $D + ' ' + $e.cost
    $lines.Add('- ' + $e.vit + ' *(' + $meta + ')*')
  }
  $lines.Add('')
}
$lines.Add($E0)
$blockLF = [string]::Join("`n", $lines)

if ($IndexOut -ne '') { [System.IO.File]::WriteAllText($IndexOut, $blockLF, $noBom) }

if ($Inject -ne '') {
  $tb = [System.IO.File]::ReadAllBytes($Inject)
  $thasBom = ($tb.Length -ge 3 -and $tb[0] -eq 0xEF -and $tb[1] -eq 0xBB -and $tb[2] -eq 0xBF)
  $s0 = if ($thasBom) { 3 } else { 0 }
  $tgt = $noBom.GetString($tb, $s0, $tb.Length - $s0)
  $nl = if ($tgt -match "`r`n") { "`r`n" } else { "`n" }
  $block = $blockLF -replace "`n", $nl
  $bi = $tgt.IndexOf('<!-- HL:BEGIN')
  $ei = $tgt.IndexOf($E0)
  if ($bi -ge 0 -and $ei -gt $bi) {
    $new = $tgt.Substring(0, $bi) + $block + $tgt.Substring($ei + $E0.Length)
    [System.IO.File]::WriteAllText($Inject, $new, (New-Object System.Text.UTF8Encoding($thasBom)))
    Write-Output ("injected: " + $Inject + " (bom=" + $thasBom + ")")
  } else {
    Write-Output "MARKERS NOT FOUND in inject target"
  }
}

Write-Output ("entries=" + $entries.Count + " index=" + $idx.Count)
